volumes:
  mongo-data:
    external: true
services:
  mongo:
      image: mongo:5
      volumes:
        - mongo-data:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: animob
        MONGO_INITDB_ROOT_PASSWORD: animob
  animob:
    build:
      context: ./animob
      dockerfile: ./Dockerfile.dev
    ports:
      - 8000:8000

    volumes:
      - ./animob:/app
    environment:
      MONGOHOST: mongo
      MONGODATABASE: animob
      MONGOUSER: animob
      MONGOPASSWORD: animob
      SIGNING_KEY: 46ce38c45265e6a9547838588094eae4b2bff48c2e6d45f21d381f686a89cb65
      SIGNING_KEY: 46ce38c45265e6a9547838588094eae4b2bff48c2e6d45f21d381f686a89cb65
      DATABASE_URL: mongodb://root:password@mongo
      DATABASE_NAME: animob-data
      WAIT_HOSTS: mongo:27017
      WAIT_BEFORE: 5
      WAIT_TIMEOUT: 60

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      REACT_APP_SAMPLE_SERVICE_API_HOST: http://localhost:8000
